services:
  frontend:
    build: ./frontend
    ports:
      - 8080:80
    depends_on:
      - db

  game-simulation:
    build: ./game-simulation
    ports:
      - 8081:80
    depends_on:
      - db

  stat-api-server:
    build: ./stat-api-server
    ports:
      - 8082:80
    depends_on:
      - db

  db:
    build: ./stat-db
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:8
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 8083:80
    depends_on:
      - db

volumes:
  db-data: