name: Test stat API server

on:
  push:
    branches: [ "main" ]
    paths: [ 'stat-api-server/**' ]
  pull_request:
    branches: [ "main" ]
    paths: [ 'stat-api-server/**' ]
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Build
      run: |
        cd stat-api-server
        go build -v ./...

    - name: Test
      run: |
        cd stat-api-server
        go test -v ./...
